###################################AVIRIS_FLIGHT_LINES####################################
library(raster)
library(spectrolab)

##Reads in Imagery as multi layer raster
Clayton_AVIRIS_Tiff_Spatial<-brick("Imagery/Spectral_Subset_2019_05_15T22_29_34Z_Area0.dat")

##Marks raster as unrotated
Clayton_AVIRIS_Tiff_Spatial@rotated<-FALSE

##Converts raster layer to combined dataframe to dataframe
Clayton_AVIRIS_Tiff_df<-rasterToPoints(Clayton_AVIRIS_Tiff_Spatial)%>% as.data.frame()

##Reads in bandpasses for imagery
AVIRIS_ng_wv        <-scan("Processed_imagery/AVIRIS/AVIRIS_WVLs", numeric())

##Reads in spectral library as .rda
AK2018_spectra      <- readRDS("Processed_spec/Alaska_Summer_2018/AK2018/AK2018_spectra.rds")
bethelLib_spectra   <- readRDS("Processed_spec/Alaska_Summer_2018/bethelLib/bethelLib_spectra.rds")
brooksLib_spectra   <- readRDS("Processed_spec/Alaska_Summer_2018/brooksLib/brooksLib_spectra.rds")
Murph2_spectra      <- readRDS("Processed_spec/Alaska_Summer_2018/Murph2_Lib/Murph2_spectra.rds")
Murph_lib_spectra   <- readRDS("Processed_spec/Alaska_Summer_2018/Murph_lib/Murph_lib_spectra.rds")
yKDeltLib_spectra   <- readRDS("Processed_spec/Alaska_Summer_2018/yKDeltLib/yKDeltLib_spectra.rds")

##Resample spectral library based on Imagery bandpasses
AK2018_spectra_AV   <-as.data.frame(AK2018_spectra_AV)
bethelLib_spectra_AV<-as.data.frame(bethelLib_spectra_AV)
brooksLib_spectra_AV<-as.data.frame(brooksLib_spectra_AV)
Murph2_spectra_AV   <-as.data.frame(Murph2_spectra_AV)
Murph_lib_spectra_AV<-as.data.frame(Murph_lib_spectra_AV)
yKDeltLib_spectra_AV<-as.data.frame(yKDeltLib_spectra_AV)

##Converts resampled spectral library to dataframe
AK2018_spectra_AV   <-as.data.frame(AK2018_spectra_AV)
bethelLib_spectra_AV<-as.data.frame(bethelLib_spectra_AV)
brooksLib_spectra_AV<-as.data.frame(brooksLib_spectra_AV)
Murph2_spectra_AV   <-as.data.frame(Murph2_spectra_AV)
Murph_lib_spectra_AV<-as.data.frame(Murph_lib_spectra_AV)
yKDeltLib_spectra_AV<-as.data.frame(yKDeltLib_spectra_AV)


##Combines all dataframes from previous step
alaskaSpecLib_AV_all<-rbind(AK2018_spectra_AV,
                        bethelLib_spectra_AV,
                        brooksLib_spectra_AV,
                        Murph2_spectra_AV,
                        Murph_lib_spectra_AV,
                        yKDeltLib_spectra_AV)

###deletes col "sample_name"
alaskaSpecLib_AV_all$sample_name<-NULL

#Changes band names so they'll correspond to the ones from the images
colnames(alaskaSpecLib_AV_all)[-(1:3)]<-c(colnames(Clayton_AVIRIS_Tiff_df)[-(1:2)])

##Add column PFT_2 (SPECIES)
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="aleoch"]<-"Alectoria ochroleuca"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="alnfru"]<-"Alnus sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="arccen"]<-"Arctocetraria centrifuga"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="arcnig"]<-"Arctostaphyllos"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="arcrub"]<-"Arctostaphyllos"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="arcsta"]<-"Arctostaphyllos"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="arctop"]<-"Unknown"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="asachr"]<-"Asahinea chrysantha"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="aulpal"]<-"Aulacomnium palustre"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="aultur"]<-"Aulacomnium turgidum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="bare rock"]<-"Bare Rock"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="bare_soil"]<-"Bare Soil"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="betnan"]<-"Betula nana"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="betneo"]<-"Betula neoalaskana"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="bryoria"]<-"Bryoria sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="calcan"]<-"Calamogrostis sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="carlin"]<-"Carex sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="carlyn"]<-"Carex sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="carram"]<-"Carex sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="cerpur"]<-"Ceratadon purpureus"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="cetisl"]<-"Cetraria islandica"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="cetlae"]<-"Cetraria laevigata"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="claama"]<-"Cladonia amaurocraea"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="clacor"]<-"Cladonia cornuta"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="clacuc"]<-"FlAVocetraria cucculata"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="clagra"]<-"Cladonia gracilis"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="clamit"]<-"Cladonia mitis"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="claran"]<-"Cladonia rangiferina"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="claste"]<-"Cladonia steallaris"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="clasty"]<-"Cladonia stygia"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="clasul"]<-"Cladonia sulphurina"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="claunc"]<-"Cladonia uncialis"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="dead salix"]<-"Dead Salix"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="dicranum"]<-"Dicranum sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="empnig"]<-"Empetrum nigrum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="equarv"]<-"Equisetum arvense"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="equsyl"]<-"Equisetum sylvaticum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="erivag"]<-"Eriophorum vaginatum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="evemes"]<-"Evernia mesomorpha"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="flacuc"]<-"FlAVocetraria cucculata"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="flaniv"]<-"FlAVocetraria nivalis"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="gravel"]<-"gravel"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="grey_rhizocarpon"]<-"Rhizocarpon sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="herlan"]<-"Heracleum lanatum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="hylspl"]<-"Hylocomium splendens"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="hypaus"]<-"Hypogymnia austerodes"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="hypspl"]<-"Hylocomium splendens"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="icmeri"]<-"Icmadophila ericetorum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="irisit"]<-"Iris sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="leddec"]<-"Ledum decumbens"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="loipro"]<-"Loisleuria procumbens"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="luparc"]<-"Lupinus sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="masric"]<-"Masonhalea richardsonii"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="melanelia"]<-"Melanelia sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="melhep"]<-"Melanelia sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="neparc"]<-"Nephroma arcticum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="naparc"]<-"Nephroma arcticum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="orange_Porpidia"]<-"Porpidia sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="paramb"]<-"Parmeliopsis ambigua"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="paromp"]<-"Parmelia omphalodes"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="parsul"]<-"Parmelis sulcata"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="pedrac"]<-"Pedicularis racemosa"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="pedsud"]<-"Pedicularis sudetica"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="pelapt"]<-"Peltigera apthosa"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="pelleu"]<-"Peltigers leucophlebia"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="pelmal"]<-"Peltigera malacea"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="pelsca"]<-"Peltigera scabrata"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="petfri"]<-"Petasites frigida"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="picmar"]<-"Picea mariana"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="plagiomnium"]<-"Plagiomnium sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="plesch"]<-"Pleurozium schreberi"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="poljen"]<-"Polytrichum juniperinum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="poljun"]<-"Polytrichum juniperinum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="polstr"]<-"Polytrichum strictum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="polytrichum"]<-"Polytrichum sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="popbal"]<-"Populus balsamifera"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="quartz"]<-"Quartz"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="raclan"]<-"Racomitrium lanoiginosum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="rhigeo"]<-"Rhizocarpon geographicum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="rhyrug"]<-"Rhytidum rugosum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="rosasc"]<-"Rosa acicularis"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="rubcam"]<-"Rubus sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="rubcha"]<-"Rubus sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="salala"]<-"Salix alaxensis"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="salarb"]<-"Salix arbusculoides"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="salgla"]<-"Salix glauca"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="sallan"]<-"Salix lanata"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="salova"]<-"Salix ovalifolia"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="Salova"]<-"Salix ovalifolia"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="salpul"]<-"Salix pulchra"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="salric"]<-"Salix richardsonii"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="sphagn"]<-"Sphagnum sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="sphfus"]<-"Sphagnum fuscum"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="spruce bark"]<-"Pices (bark)"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="stepas"]<-"Stereocaulon sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="stetas"]<-"Stereocaulon sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="toefeldia"]<-"Toefeldia sp."
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="tomnit"]<-"Tomenthypnum nitens"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="tragra"]<-"Trapelopsis granulosa"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="umbarc"]<-"Umbilicaria arctica"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="umbhyp"]<-"Umbilicaria hyperborea"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="usnlap"]<-"Usnea lapponica"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="usnsca"]<-"Usnea scabrata"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="vacvit"]<-"Vaccinium vitis-idea"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="vulpin"]<-"Vulpicida pinastri"
alaskaSpecLib_AV_all$PFT_2[alaskaSpecLib_AV_all$PFT=="wooly_salix"]<-"Salix (wooly)"

###Add column PFT_3 (Couser response variables)
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="aleoch"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="alnfru"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arccen"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arcnig"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arcrub"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arcsta"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arctop"]<-"Unknown"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="asachr"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="aulpal"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="aultur"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="bare rock"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="bare_soil"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="betnan"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="betneo"]<-"Tree"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="bryoria"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="calcan"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="carlin"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="carlyn"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="carram"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="cerpur"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="cetisl"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="cetlae"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="claama"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clacor"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clacuc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clagra"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clamit"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="claran"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="claste"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clasty"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clasul"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="claunc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="dead salix"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="dicranum"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="empnig"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="equarv"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="equsyl"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="erivag"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="evemes"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="flacuc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="flaniv"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="gravel"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="grey_rhizocarpon"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="herlan"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="hylspl"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="hypaus"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="hypspl"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="icmeri"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="irisit"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="leddec"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="loipro"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="luparc"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="masric"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="melanelia"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="melhep"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="neparc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="naparc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="orange_Porpidia"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="paramb"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="paromp"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="parsul"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pedrac"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pedsud"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pelapt"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pelleu"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pelmal"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pelsca"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="petfri"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="picmar"]<-"Tree"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="plagiomnium"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="plesch"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="poljen"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="poljun"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="polstr"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="polytrichum"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="popbal"]<-"Tree"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="quartz"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="raclan"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rhigeo"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rhyrug"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rosasc"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rubcam"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rubcha"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salala"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salarb"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salgla"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="sallan"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salova"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="Salova"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salpul"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salric"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="sphagn"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="sphfus"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="spruce bark"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="stepas"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="stetas"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="toefeldia"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="tomnit"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="tragra"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="umbarc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="umbhyp"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="usnlap"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="usnsca"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="vacvit"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="vulpin"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="wooly_salix"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="aleoch"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="alnfru"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arccen"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arcnig"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arcrub"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arcsta"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="arctop"]<-"Unknown"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="asachr"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="aulpal"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="aultur"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="bare rock"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="bare_soil"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="betnan"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="betneo"]<-"Tree"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="bryoria"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="calcan"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="carlin"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="carlyn"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="carram"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="cerpur"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="cetisl"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="cetlae"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="claama"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clacor"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clacuc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clagra"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clamit"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="claran"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="claste"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clasty"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="clasul"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="claunc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="dead salix"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="dicranum"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="empnig"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="equarv"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="equsyl"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="erivag"]<-"Graminoid"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="evemes"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="flacuc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="flaniv"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="gravel"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="grey_rhizocarpon"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="herlan"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="hylspl"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="hypaus"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="hypspl"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="icmeri"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="irisit"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="leddec"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="loipro"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="luparc"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="masric"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="melanelia"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="melhep"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="neparc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="naparc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="orange_Porpidia"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="paramb"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="paromp"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="parsul"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pedrac"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pedsud"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pelapt"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pelleu"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pelmal"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="pelsca"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="petfri"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="picmar"]<-"Tree"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="plagiomnium"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="plesch"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="poljen"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="poljun"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="polstr"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="polytrichum"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="popbal"]<-"Tree"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="quartz"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="raclan"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rhigeo"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rhyrug"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rosasc"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rubcam"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="rubcha"]<-"Dwarf Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salala"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salarb"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salgla"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="sallan"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salova"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="Salova"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salpul"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="salric"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="sphagn"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="sphfus"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="spruce bark"]<-"Abiotic"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="stepas"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="stetas"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="toefeldia"]<-"Forb"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="tomnit"]<-"Moss"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="tragra"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="umbarc"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="umbhyp"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="usnlap"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="usnsca"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="vacvit"]<-"Shrub"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="vulpin"]<-"Lichen"
alaskaSpecLib_AV_all$PFT_3[alaskaSpecLib_AV_all$PFT=="wooly_salix"]<-"Shrub"

#Plants only
alaskaSpecLib_AV_plants<-subset(alaskaSpecLib_AV_all,PFT_3!="Abiotic")

##Extracts scans for each life form (lichen, bryophyte, vascular plant) for spectral library to use in imagery prediction
alaskaSpecLib_AV_lichen     <-subset(alaskaSpecLib_AV_plants,PFT_3=="Lichen")
alaskaSpecLib_AV_bryo       <-subset(alaskaSpecLib_AV_plants,PFT_3=="Moss")
alaskaSpecLib_AV_lichen_bryo<-subset(alaskaSpecLib_AV_plants,PFT_3=="Lichen"|PFT_3=="Moss")
alaskaSpecLib_AV_vascular   <-subset(alaskaSpecLib_AV_plants,PFT_3!="Lichen"&PFT_3!="Moss")


##Save spectral Library to be used in imagery prediction 
write.csv(Clayton_AVIRIS_Tiff_df      ,"Processed_spec/Library/Raw/Clayton_AVIRIS_Tiff_df.csv",row.names= FALSE)
write.csv(alaskaSpecLib_AV_all        ,"Processed_spec/Library/Raw/alaskaSpecLib_AV_all.csv",row.names = FALSE)
write.csv(alaskaSpecLib_AV_plants     ,"Processed_spec/Library/Raw/alaskaSpecLib_AV_plants.csv",row.names = FALSE)
write.csv(alaskaSpecLib_AV_lichen     ,"Processed_spec/Library/Raw/alaskaSpecLib_AV_lichen.csv",row.names = FALSE)
write.csv(alaskaSpecLib_AV_bryo       ,"Processed_spec/Library/Raw/alaskaSpecLib_AV_bryo.csv",row.names = FALSE)
write.csv(alaskaSpecLib_AV_lichen_bryo,"Processed_spec/Library/Raw/alaskaSpecLib_AV_lichen_bryo.csv",row.names = FALSE)
write.csv(alaskaSpecLib_AV_vascular   ,"Processed_spec/Library/Raw/alaskaSpecLib_AV_vascular.csv",row.names = FALSE)
