# Creates a dataframe with all species and their corresponding functional groups
library (tidyverse)

# Creates column PFT
SpecLib_groups<-data.frame("PFT"= c("abibal"
                                   ,"acerub"
                                   ,"acepen"
                                   ,"aleoch"
                                   ,"alnfru"
                                   ,"alninc"
                                   ,"arccen"
                                   ,"arcnig"
                                   ,"arcrub"
                                   ,"arcsta"
                                   ,"arctop"
                                   ,"asachr"
                                   ,"aulpal"
                                   ,"aultur"
                                   ,"bare rock"
                                   ,"bare_soil"
                                   ,"betall"
                                   ,"betnan"
                                   ,"betneo"
                                   ,"betpap"
                                   ,"betpop"
                                   ,"bryoria"
                                   ,"calcan"
                                   ,"carlin"
                                   ,"carlyn"
                                   ,"carram"
                                   ,"castet"
                                   ,"cerpur"
                                   ,"cetisl"
                                   ,"cetlae"
                                   ,"claama"
                                   ,"clacor"
                                   ,"clacuc"
                                   ,"clagra"
                                   ,"clamit"
                                   ,"claran"
                                   ,"claste"
                                   ,"clasty"
                                   ,"clasul"
                                   ,"claunc"
                                   ,"dacarc"
                                   ,"dead salix"
                                   ,"dicranum"
                                   ,"dryala"
                                   ,"dryhyb"
                                   ,"dryoct"
                                   ,"empnig"
                                   ,"equarv"
                                   ,"equsyl"
                                   ,"erivag"
                                   ,"evemes"
                                   ,"faggra"
                                   ,"flacuc"
                                   ,"flaniv"
                                   ,"fraame"
                                   ,"gravel"
                                   ,"grey_rhizocarpon"
                                   ,"herlan"
                                   ,"hylspl"
                                   ,"hypaus"
                                   ,"hypspl"
                                   ,"icmeri"
                                   ,"irisit"
                                   ,"larlar"
                                   ,"leddec"
                                   ,"loipro"
                                   ,"luparc"
                                   ,"masric"
                                   ,"melanelia"
                                   ,"melhep"
                                   ,"neparc"
                                   ,"naparc"
                                   ,"orange_Porpidia"
                                   ,"paramb"
                                   ,"paromp"
                                   ,"parsul"
                                   ,"pedrac"
                                   ,"pedsud"
                                   ,"pelapt"
                                   ,"pelleu"
                                   ,"pelmal"
                                   ,"pelsca"
                                   ,"petfri"
                                   ,"picmar"
                                   ,"picrub"
                                   ,"pilaci"
                                   ,"pinstr"
                                   ,"plagiomnium"
                                   ,"popbal"
                                   ,"popgra"
                                   ,"prupen"
                                   ,"plesch"
                                   ,"poljen"
                                   ,"poljun"
                                   ,"polstr"
                                   ,"polytrichum"
                                   ,"popbal"
                                   ,"quartz"
                                   ,"querub"
                                   ,"raclan"
                                   ,"rhigeo"
                                   ,"rhyrug"
                                   ,"rhutyp"
                                   ,"rosaci"
                                   ,"rosasc"
                                   ,"rubcam"
                                   ,"rubcha"
                                   ,"salala"
                                   ,"salarb"
                                   ,"salgla"
                                   ,"sallan"
                                   ,"salova"
                                   ,"Salova"
                                   ,"salpul"
                                   ,"salric"
                                   ,"sphagn"
                                   ,"sphfus"
                                   ,"spruce bark"
                                   ,"stepas"
                                   ,"stetas"
                                   ,"thuocc"
                                   ,"toefeldia"
                                   ,"tomnit"
                                   ,"tragra"
                                   ,"tsucan"
                                   ,"umbarc"
                                   ,"umbhyp"
                                   ,"usnlap"
                                   ,"usnsca"
                                   ,"vacvit"
                                   ,"vaculi"
                                   ,"vulpin"
                                   ,"wooly_salix"))

# Add column PFT_2 (SPECIES) to spectral library
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="abibal"]<-"Abies balsamea"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="acerub"]<-"Acer rubrum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="acepen"]<-"Acer pensylvanicum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="aleoch"]<-"Alectoria ochroleuca"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="alnfru"]<-"Alnus sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="alninc"]<-"Alnus Incana"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="arccen"]<-"Arctocetraria centrifuga"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="arcnig"]<-"Arctostaphyllos"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="arcrub"]<-"Arctostaphyllos"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="arcsta"]<-"Arctostaphyllos"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="arctop"]<-"Unknown"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="asachr"]<-"Asahinea chrysantha"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="aulpal"]<-"Aulacomnium palustre"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="aultur"]<-"Aulacomnium turgidum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="bare rock"]<-"Bare Rock"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="bare_soil"]<-"Bare Soil"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="betall"]<-"Betula alleghaniensis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="betnan"]<-"Betula nana"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="betneo"]<-"Betula neoalaskana"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="betpap"]<-"Betula papyrifera"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="betpop"]<-"Betula populifolia"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="bryoria"]<-"Bryoria sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="calcan"]<-"Calamogrostis sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="carlin"]<-"Carex sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="carlyn"]<-"Carex sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="carram"]<-"Carex sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="castet"]<-"Cassiope tetragona"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="cerpur"]<-"Ceratadon purpureus"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="cetisl"]<-"Cetraria islandica"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="cetlae"]<-"Cetraria laevigata"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="claama"]<-"Cladonia amaurocraea"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="clacor"]<-"Cladonia cornuta"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="clacuc"]<-"Flavocetraria cucculata"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="clagra"]<-"Cladonia gracilis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="clamit"]<-"Cladonia mitis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="claran"]<-"Cladonia rangiferina"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="claste"]<-"Cladonia steallaris"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="clasty"]<-"Cladonia stygia"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="clasul"]<-"Cladonia sulphurina"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="claunc"]<-"Cladonia uncialis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="dacarc"]<-"Dactylina arctica"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="dead salix"]<-"Dead Salix"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="dicranum"]<-"Dicranum sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="dryala"]<-"Dryas alleghenies"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="dryhyb"]<-"Dryas sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="dryoct"]<-"Dryas octopetala"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="empnig"]<-"Empetrum nigrum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="equarv"]<-"Equisetum arvense"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="equsyl"]<-"Equisetum sylvaticum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="erivag"]<-"Eriophorum vaginatum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="evemes"]<-"Evernia mesomorpha"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="faggra"]<-"Fagus grandifolia"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="flacuc"]<-"Flavocetraria cucculata"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="flaniv"]<-"Flavocetraria nivalis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="fraame"]<-"Fraxinus americana"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="gravel"]<-"Gravel"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="grey_rhizocarpon"]<-"Rhizocarpon sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="herlan"]<-"Heracleum lanatum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="hylspl"]<-"Hylocomium splendens"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="hypaus"]<-"Hypogymnia austerodes"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="hypspl"]<-"Hylocomium splendens"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="icmeri"]<-"Icmadophila ericetorum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="irisit"]<-"Iris sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="larlar"]<-"Larix Larcina"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="leddec"]<-"Ledum decumbens"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="loipro"]<-"Loisleuria procumbens"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="luparc"]<-"Lupinus sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="masric"]<-"Masonhalea richardsonii"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="melanelia"]<-"Melanelia sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="melhep"]<-"Melanelia sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="neparc"]<-"Nephroma arcticum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="naparc"]<-"Nephroma arcticum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="orange_Porpidia"]<-"Porpidia sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="paramb"]<-"Parmeliopsis ambigua"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="paromp"]<-"Parmelia omphalodes"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="parsul"]<-"Parmelis sulcata"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="pedrac"]<-"Pedicularis racemosa"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="pedsud"]<-"Pedicularis sudetica"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="pelapt"]<-"Peltigera apthosa"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="pelleu"]<-"Peltigers leucophlebia"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="pelmal"]<-"Peltigera malacea"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="pelsca"]<-"Peltigera scabrata"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="petfri"]<-"Petasites frigida"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="picmar"]<-"Picea mariana"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="picrub"]<-"Picea rubens"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="pilaci"]<-"Pilophorus acicularis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="pinstr"]<-"Pinus strobus"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="plagiomnium"]<-"Plagiomnium sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="plesch"]<-"Pleurozium schreberi"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="poljen"]<-"Polytrichum juniperinum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="poljun"]<-"Polytrichum juniperinum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="polstr"]<-"Polytrichum strictum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="polytrichum"]<-"Polytrichum sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="popbal"]<-"Populus balsamifera"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="popgra"]<-"Populus grandidentata"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="prupen"]<-"Prunus pensylvanica"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="quartz"]<-"Quartz"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="querub"]<-"Quercus Rubra"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="raclan"]<-"Racomitrium lanoiginosum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="rhigeo"]<-"Rhizocarpon geographicum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="rhutyp"]<-"Rhus typhina"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="rhyrug"]<-"Rhytidum rugosum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="rosaci"]<-"Rosa acicularis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="rosasc"]<-"Rosa acicularis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="rubcam"]<-"Rubus sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="rubcha"]<-"Rubus sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="salala"]<-"Salix alaxensis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="salarb"]<-"Salix arbusculoides"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="salgla"]<-"Salix glauca"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="sallan"]<-"Salix lanata"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="salova"]<-"Salix ovalifolia"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="Salova"]<-"Salix ovalifolia"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="salpul"]<-"Salix pulchra"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="salric"]<-"Salix richardsonii"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="sphagn"]<-"Sphagnum sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="sphfus"]<-"Sphagnum fuscum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="spruce bark"]<-"Pices (bark)"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="stepas"]<-"Stereocaulon sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="stetas"]<-"Stereocaulon sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="thuocc"]<-"Thuja occidentalis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="toefeldia"]<-"Toefeldia sp."
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="tomnit"]<-"Tomenthypnum nitens"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="tragra"]<-"Trapelopsis granulosa"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="tsucan"]<-"Tsuga canadensis"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="umbarc"]<-"Umbilicaria arctica"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="umbhyp"]<-"Umbilicaria hyperborea"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="usnlap"]<-"Usnea lapponica"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="usnsca"]<-"Usnea scabrata"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="vacvit"]<-"Vaccinium vitis-idea"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="vaculi"]<-"Vaccinium uliginosum"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="vulpin"]<-"Vulpicida pinastri"
SpecLib_groups$PFT_2[SpecLib_groups$PFT=="wooly_salix"]<-"Salix (wooly)"

###Add column PFT_3 (Courser response variables)
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="abibal"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="acerub"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="acepen"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="aleoch"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="alnfru"]<-"Shrub_Alder"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="alninc"]<-"Shrub_Alder"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="arccen"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="arcnig"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="arcrub"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="arcsta"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="arctop"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="asachr"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="aulpal"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="aultur"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="bare rock"]<-"Abiotic_Rock"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="bare_soil"]<-"Abiotic_Soil"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="betall"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="betnan"]<-"Shrub_Other"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="betneo"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="betpap"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="betpop"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="bryoria"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="calcan"]<-"Graminoid_Grass"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="carlin"]<-"Graminoid_Sedge"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="carlyn"]<-"Graminoid_Sedge"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="carram"]<-"Graminoid_Sedge"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="castet"]<-"Dwarf_Shrub_Needle"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="cerpur"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="cetisl"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="cetlae"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="claama"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="clacor"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="clacuc"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="clagra"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="clamit"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="claran"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="claste"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="clasty"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="clasul"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="claunc"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="dacarc"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="dead salix"]<-"Abiotic_Litter"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="dicranum"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="dryala"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="dryhyb"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="dryoct"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="empnig"]<-"Dwarf_Shrub_Needle"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="equarv"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="equsyl"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="erivag"]<-"Graminoid_Sedge"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="evemes"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="faggra"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="flacuc"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="flaniv"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="fraame"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="gravel"]<-"Abiotic_Rock"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="grey_rhizocarpon"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="herlan"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="hylspl"]<-"Moss_Pleurocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="hypaus"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="hypspl"]<-"Moss_Pleurocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="icmeri"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="irisit"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="larlar"]<-"Tree_Needle"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="leddec"]<-"Shrub_Other"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="loipro"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="luparc"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="masric"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="melanelia"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="melhep"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="neparc"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="naparc"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="orange_Porpidia"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="paramb"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="paromp"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="parsul"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="pedrac"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="pedsud"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="pelapt"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="pelleu"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="pelmal"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="pelsca"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="petfri"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="picmar"]<-"Tree_Needle"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="picrub"]<-"Tree_Needle"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="pilaci"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="pinstr"]<-"Tree_Needle"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="plagiomnium"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="popbal"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="popgra"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="prupen"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="plesch"]<-"Moss_Pleurocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="poljen"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="poljun"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="polstr"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="polytrichum"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="popbal"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="quartz"]<-"Abiotic_Rock"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="querub"]<-"Tree_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="raclan"]<-"Moss_Pleurocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="rhigeo"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="rhyrug"]<-"Moss_Acrocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="rhutyp"]<-"Shrub_Other"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="rosaci"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="rosasc"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="rubcam"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="rubcha"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="salala"]<-"Shrub_Salix"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="salarb"]<-"Shrub_Salix"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="salgla"]<-"Shrub_Salix"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="sallan"]<-"Shrub_Salix"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="salova"]<-"Shrub_Salix"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="Salova"]<-"Shrub_Salix"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="salpul"]<-"Shrub_Salix"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="salric"]<-"Shrub_Salix"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="sphagn"]<-"Moss_Sphagnum"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="sphfus"]<-"Moss_Sphagnum"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="spruce bark"]<-"Abiotic_Litter"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="stepas"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="stetas"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="thuocc"]<-"Tree_Needle"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="toefeldia"]<-"Forb"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="tomnit"]<-"Moss_Pleurocarp"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="tragra"]<-"Lichen_Light"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="tsucan"]<-"Tree_Needle"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="umbarc"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="umbhyp"]<-"Lichen_Dark"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="usnlap"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="usnsca"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="vacvit"]<-"Shrub_Other"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="vaculi"]<-"Dwarf_Shrub_Broad"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="vulpin"]<-"Lichen_Yellow"
SpecLib_groups$PFT_3[SpecLib_groups$PFT=="wooly_salix"]<-"Shrub_Salix"

###Add column PFT_4 (Courser than PFT3 response variables)
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="abibal"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="acerub"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="acepen"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="aleoch"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="alnfru"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="alninc"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="arccen"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="arcnig"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="arcrub"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="arcsta"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="arctop"]<-"Unknown"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="asachr"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="aulpal"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="aultur"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="bare rock"]<-"Abiotic"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="bare_soil"]<-"Abiotic"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="betall"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="betnan"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="betneo"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="betpap"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="betpop"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="bryoria"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="calcan"]<-"Graminoid"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="carlin"]<-"Graminoid"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="carlyn"]<-"Graminoid"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="carram"]<-"Graminoid"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="castet"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="cerpur"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="cetisl"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="cetlae"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="claama"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="clacor"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="clacuc"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="clagra"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="clamit"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="claran"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="claste"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="clasty"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="clasul"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="claunc"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="dacarc"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="dead salix"]<-"Abiotic"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="dicranum"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="dryala"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="dryhyb"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="dryoct"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="empnig"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="equarv"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="equsyl"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="erivag"]<-"Graminoid"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="evemes"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="faggra"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="flacuc"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="flaniv"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="fraame"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="gravel"]<-"Abiotic"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="grey_rhizocarpon"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="herlan"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="hylspl"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="hypaus"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="hypspl"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="icmeri"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="irisit"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="larlar"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="leddec"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="loipro"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="luparc"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="masric"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="melanelia"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="melhep"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="neparc"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="naparc"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="orange_Porpidia"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="paramb"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="paromp"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="parsul"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="pedrac"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="pedsud"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="pelapt"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="pelleu"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="pelmal"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="pelsca"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="petfri"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="picmar"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="picrub"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="pilaci"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="pinstr"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="plagiomnium"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="popbal"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="popgra"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="prupen"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="plesch"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="poljen"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="poljun"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="polstr"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="polytrichum"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="popbal"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="quartz"]<-"Abiotic"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="querub"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="raclan"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="rhigeo"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="rhyrug"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="rhutyp"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="rosaci"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="rosasc"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="rubcam"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="rubcha"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="salala"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="salarb"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="salgla"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="sallan"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="salova"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="Salova"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="salpul"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="salric"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="sphagn"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="sphfus"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="spruce bark"]<-"Abiotic"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="stepas"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="stetas"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="thuocc"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="toefeldia"]<-"Forb"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="tomnit"]<-"Moss"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="tragra"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="tsucan"]<-"Tree"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="umbarc"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="umbhyp"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="usnlap"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="usnsca"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="vacvit"]<-"Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="vaculi"]<-"Dwarf Shrub"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="vulpin"]<-"Lichen"
SpecLib_groups$PFT_4[SpecLib_groups$PFT=="wooly_salix"]<-"Shrub"

write.csv(SpecLib_groups,"OutputsPSR/Processing/PSR/SpecLib_groups.csv",row.names = F)
