## ------------------------------------------------------- Script_1 -------------------------------------------------------------------##
# Creates a dataframe with all species and their corresponding functional groups
# The final table will have 4 columns (Code_name, species name, Functional_group1 and functional_group2)

# Packages to install
library(plyr)
library (tidyverse) 


# Code_Name = Six letter code for each species, first three letters represents the genus name and second three represents the species name
SpecLib_groups<-data.frame("Code_name"= c("abibal"
                                         ,"acerub"
                                         ,"acepen"
                                         ,"aleoch"
                                         ,"alnfru"
                                         ,"alninc"
                                         ,"arccen"
                                         ,"arcnig"
                                         ,"arcrub"
                                         ,"arcsta"
                                         ,"arctop"
                                         ,"asachr"
                                         ,"aulpal"
                                         ,"aultur"
                                         ,"bare rock"
                                         ,"bare_soil"
                                         ,"betall"
                                         ,"betnan"
                                         ,"betneo"
                                         ,"betpap"
                                         ,"betpop"
                                         ,"bryoria"
                                         ,"calcan"
                                         ,"carlin"
                                         ,"carlyn"
                                         ,"carram"
                                         ,"castet"
                                         ,"cerpur"
                                         ,"cetisl"
                                         ,"cetlae"
                                         ,"claama"
                                         ,"clacor"
                                         ,"clacuc"
                                         ,"clagra"
                                         ,"clamit"
                                         ,"claran"
                                         ,"claste"
                                         ,"clasty"
                                         ,"clasul"
                                         ,"claunc"
                                         ,"dacarc"
                                         ,"dead salix"
                                         ,"dicranum"
                                         ,"dryala"
                                         ,"dryhyb"
                                         ,"dryoct"
                                         ,"empnig"
                                         ,"equarv"
                                         ,"equsyl"
                                         ,"erivag"
                                         ,"evemes"
                                         ,"faggra"
                                         ,"flacuc"
                                         ,"flaniv"
                                         ,"fraame"
                                         ,"gravel"
                                         ,"grey_rhizocarpon"
                                         ,"herlan"
                                         ,"hylspl"
                                         ,"hypaus"
                                         ,"hypspl"
                                         ,"icmeri"
                                         ,"irisit"
                                         ,"larlar"
                                         ,"leddec"
                                         ,"loipro"
                                         ,"luparc"
                                         ,"masric"
                                         ,"melanelia"
                                         ,"melhep"
                                         ,"neparc"
                                         ,"naparc"
                                         ,"orange_Porpidia"
                                         ,"paramb"
                                         ,"paromp"
                                         ,"parsul"
                                         ,"pedrac"
                                         ,"pedsud"
                                         ,"pelapt"
                                         ,"pelleu"
                                         ,"pelmal"
                                         ,"pelsca"
                                         ,"petfri"
                                         ,"picmar"
                                         ,"picrub"
                                         ,"pilaci"
                                         ,"pinstr"
                                         ,"plagiomnium"
                                         ,"popbal"
                                         ,"popgra"
                                         ,"prupen"
                                         ,"plesch"
                                         ,"poljen"
                                         ,"poljun"
                                         ,"polstr"
                                         ,"polytrichum"
                                         ,"popbal"
                                         ,"quartz"
                                         ,"querub"
                                         ,"raclan"
                                         ,"rhigeo"
                                         ,"rhyrug"
                                         ,"rhutyp"
                                         ,"rosaci"
                                         ,"rosasc"
                                         ,"rubcam"
                                         ,"rubcha"
                                         ,"salala"
                                         ,"salarb"
                                         ,"salgla"
                                         ,"sallan"
                                         ,"salova"
                                         ,"Salova"
                                         ,"salpul"
                                         ,"salric"
                                         ,"sphagn"
                                         ,"sphfus"
                                         ,"spruce bark"
                                         ,"stepas"
                                         ,"stetas"
                                         ,"thuocc"
                                         ,"toefeldia"
                                         ,"tomnit"
                                         ,"tragra"
                                         ,"tsucan"
                                         ,"umbarc"
                                         ,"umbhyp"
                                         ,"usnlap"
                                         ,"usnsca"
                                         ,"vacvit"
                                         ,"vaculi"
                                         ,"vulpin"
                                         ,"wooly_salix"
                                         ,"SAPU15"
                                         ,"PEFR5"
                                         ,"SAPU6"
                                         ,"ARFU2"
                                         ,"DUFI"
                                         ,"CAAQ"
                                         ,"ARLA2"
                                         ,"ERAN6"
                                         ,"VAVI"
                                         ,"ALVI5"       
                                         ,"ARALA7"        
                                         ,"BEGL"      
                                         ,"BENA"      
                                         ,"BEPU4"        
                                         ,"DAFRF"        
                                         ,"DOFR"      
                                         ,"DROCA2"        
                                         ,"EMNI"      
                                         ,"EQAR"      
                                         ,"ERVA4"        
                                         ,"HIERA"        
                                         ,"KAPR"      
                                         ,"LEDUM"        
                                         ,"RUCH"      
                                         ,"SAG"      
                                         ,"SAPH"      
                                         ,"SARI4"        
                                         ,"VAUL"      ))

# Add column Species_name (SPECIES) to spectral library
# PRN This is also hard coded. How to automate from user input?
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="abibal"]<-"Abies balsamea"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="acerub"]<-"Acer rubrum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="acepen"]<-"Acer pensylvanicum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="aleoch"]<-"Alectoria ochroleuca"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="alnfru"]<-"Alnus sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="alninc"]<-"Alnus sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="arccen"]<-"Arctocetraria centrifuga"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="arcnig"]<-"Arctostaphyllos"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="arcrub"]<-"Arctostaphyllos"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="arcsta"]<-"Arctostaphyllos"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="arctop"]<-"Unknown"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="asachr"]<-"Asahinea chrysantha"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="aulpal"]<-"Aulacomnium palustre"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="aultur"]<-"Aulacomnium turgidum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="bare rock"]<-"Bare Rock"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="bare_soil"]<-"Bare Soil"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="betall"]<-"Betula alleghaniensis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="betnan"]<-"Betula nana"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="betneo"]<-"Betula neoalaskana"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="betpap"]<-"Betula papyrifera"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="betpop"]<-"Betula populifolia"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="bryoria"]<-"Bryoria sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="calcan"]<-"Calamogrostis sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="carlin"]<-"Carex sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="carlyn"]<-"Carex sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="carram"]<-"Carex sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="castet"]<-"Cassiope tetragona"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="cerpur"]<-"Ceratadon purpureus"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="cetisl"]<-"Cetraria islandica"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="cetlae"]<-"Cetraria laevigata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="claama"]<-"Cladonia amaurocraea"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="clacor"]<-"Cladonia cornuta"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="clacuc"]<-"Flavocetraria cucculata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="clagra"]<-"Cladonia gracilis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="clamit"]<-"Cladonia mitis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="claran"]<-"Cladonia rangiferina"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="claste"]<-"Cladonia steallaris"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="clasty"]<-"Cladonia stygia"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="clasul"]<-"Cladonia sulphurina"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="claunc"]<-"Cladonia uncialis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="dacarc"]<-"Dactylina arctica"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="dead salix"]<-"Dead Salix"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="dicranum"]<-"Dicranum sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="dryala"]<-"Dryas sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="dryhyb"]<-"Dryas sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="dryoct"]<-"Dryas sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="empnig"]<-"Empetrum nigrum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="equarv"]<-"Equisetum arvense"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="equsyl"]<-"Equisetum sylvaticum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="erivag"]<-"Eriophorum vaginatum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="evemes"]<-"Evernia mesomorpha"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="faggra"]<-"Fagus grandifolia"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="flacuc"]<-"Flavocetraria cucculata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="flaniv"]<-"Flavocetraria nivalis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="fraame"]<-"Fraxinus americana"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="gravel"]<-"Bare Soil"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="grey_rhizocarpon"]<-"Rhizocarpon sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="herlan"]<-"Heracleum lanatum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="hylspl"]<-"Hylocomium splendens"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="hypaus"]<-"Hypogymnia austerodes"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="hypspl"]<-"Hylocomium splendens"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="icmeri"]<-"Icmadophila ericetorum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="irisit"]<-"Iris sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="larlar"]<-"Larix larcina"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="leddec"]<-"Ledum decumbens"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="loipro"]<-"Loisleuria procumbens"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="luparc"]<-"Lupinus sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="masric"]<-"Masonhalea richardsonii"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="melanelia"]<-"Melanelia sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="melhep"]<-"Melanelia sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="neparc"]<-"Nephroma arcticum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="naparc"]<-"Nephroma arcticum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="orange_Porpidia"]<-"Porpidia sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="paramb"]<-"Parmeliopsis ambigua"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="paromp"]<-"Parmelia omphalodes"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="parsul"]<-"Parmelis sulcata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="pedrac"]<-"Pedicularis racemosa"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="pedsud"]<-"Pedicularis sudetica"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="pelapt"]<-"Peltigera apthosa"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="pelleu"]<-"Peltigers leucophlebia"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="pelmal"]<-"Peltigera malacea"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="pelsca"]<-"Peltigera scabrata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="petfri"]<-"Petasites frigida"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="picmar"]<-"Picea mariana"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="picrub"]<-"Picea rubens"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="pilaci"]<-"Pilophorus acicularis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="pinstr"]<-"Pinus strobus"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="plagiomnium"]<-"Plagiomnium sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="plesch"]<-"Pleurozium schreberi"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="poljen"]<-"Polytrichum juniperinum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="poljun"]<-"Polytrichum juniperinum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="polstr"]<-"Polytrichum strictum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="polytrichum"]<-"Polytrichum sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="popbal"]<-"Populus balsamifera"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="popgra"]<-"Populus grandidentata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="prupen"]<-"Prunus pensylvanica"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="quartz"]<-"Quartz"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="querub"]<-"Quercus Rubra"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="raclan"]<-"Racomitrium lanoiginosum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="rhigeo"]<-"Rhizocarpon geographicum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="rhutyp"]<-"Rhus typhina"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="rhyrug"]<-"Rhytidum rugosum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="rosaci"]<-"Rosa acicularis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="rosasc"]<-"Rosa acicularis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="rubcam"]<-"Rubus sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="rubcha"]<-"Rubus sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="salala"]<-"Salix alaxensis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="salarb"]<-"Salix arbusculoides"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="salgla"]<-"Salix glauca"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="sallan"]<-"Salix lanata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="salova"]<-"Salix ovalifolia"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="Salova"]<-"Salix ovalifolia"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="salpul"]<-"Salix pulchra"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="salric"]<-"Salix richardsonii"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="sphagn"]<-"Sphagnum sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="sphfus"]<-"Sphagnum fuscum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="spruce bark"]<-"Pices (bark)"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="stepas"]<-"Stereocaulon sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="stetas"]<-"Stereocaulon sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="thuocc"]<-"Thuja occidentalis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="toefeldia"]<-"Toefeldia sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="tomnit"]<-"Tomenthypnum nitens"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="tragra"]<-"Trapelopsis granulosa"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="tsucan"]<-"Tsuga canadensis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="umbarc"]<-"Umbilicaria arctica"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="umbhyp"]<-"Umbilicaria hyperborea"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="usnlap"]<-"Usnea lapponica"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="usnsca"]<-"Usnea scabrata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="vacvit"]<-"Vaccinium vitis-idea"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="vaculi"]<-"Vaccinium uliginosum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="vulpin"]<-"Vulpicida pinastri"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="wooly_salix"]<-"Salix (wooly)"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="SAPU15"]<-"Salix pulchra"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="PEFR5"]<-"Pestasites frigidus"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="SAPU6"]<-"Saxifraga punctata"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="ARFU2"]<-"Arctophila fulva"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="DUFI"]<-"Dupontia fisheri"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="CAAQ"]<-"Carex aquatilis"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="ARLA2"]<-"Arctagrostis latifolia"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="ERAN6"]<-"Eriophorum angustifolium"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="VAVI"]<-"Vaccinium vitis-idea"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="ALVI5" ]<-"Alnus sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="ARALA7"]<-"Arctostaphyllos"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="BEGL"  ]<-"Betula nana"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="BENA"  ]<-"Betula nana"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="BEPU4" ]<-"Betula nana"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="DAFRF" ]<-"Unknown"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="DOFR"  ]<-"Arenaria pseudofrigida"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="DROCA2"]<-"Dryas sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="EMNI"  ]<-"Empetrum nigrum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="EQAR"  ]<-"Equisetum arvense"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="ERVA4" ]<-"Eriophorum vaginatum"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="HIERA" ]<-"Hieracium sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="KAPR"  ]<-"Loisleuria procumbens"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="LEDUM" ]<-"Ledum decumbens"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="RUCH"  ]<-"Rubus sp."
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="SAG"   ]<-"Unknown"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="SAPH"  ]<-"Salix phlebophylla"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="SARI4" ]<-"Salix richardsonii"
SpecLib_groups$Species_name[SpecLib_groups$Code_name=="VAUL"  ]<-"Vaccinium uliginosum"




###Add column Functional_group1 (Courser response variables)
# PRN This is hard coded. We should be using a look up table for functional group (Class 3) each plant species (Class 2) is.
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="abibal"]<-"Tree_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="acerub"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="acepen"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="aleoch"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="alnfru"]<-"Shrub_Alder"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="alninc"]<-"Shrub_Alder"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="arccen"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="arcnig"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="arcrub"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="arcsta"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="arctop"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="asachr"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="aulpal"]<-"Moss_Aulacomnium"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="aultur"]<-"Moss_Aulacomnium"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="bare rock"]<-"Rock"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="bare_soil"]<-"Soil"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="betall"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="betnan"]<-"Shrub_Betula"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="betneo"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="betpap"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="betpop"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="bryoria"]<-"Lichen_Epiphyte_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="calcan"]<-"Graminoid_Grass"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="carlin"]<-"Graminoid_Sedge"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="carlyn"]<-"Graminoid_Sedge"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="carram"]<-"Graminoid_Sedge"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="castet"]<-"Shrub_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="cerpur"]<-"Moss_Ceratadon"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="cetisl"]<-"Lichen_Fruticose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="cetlae"]<-"Lichen_Fruticose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="claama"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="clacor"]<-"Lichen_Fruticose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="clacuc"]<-"Lichen_Fruticose_Dark" #Check this. Might actually be flacuc
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="clagra"]<-"Lichen_Fruticose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="clamit"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="claran"]<-"Lichen_Fruticose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="claste"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="clasty"]<-"Lichen_Fruticose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="clasul"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="claunc"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="dacarc"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="dead salix"]<-"Litter"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="dicranum"]<-"Moss_Dicranum"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="dryala"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="dryhyb"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="dryoct"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="empnig"]<-"Shrub_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="equarv"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="equsyl"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="erivag"]<-"Graminoid_Sedge"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="evemes"]<-"Lichen_Epiphyte_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="faggra"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="flacuc"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="flaniv"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="fraame"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="gravel"]<-"Soil"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="grey_rhizocarpon"]<-"Lichen_Crustose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="herlan"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="hylspl"]<-"Moss_Hylocomnium"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="hypaus"]<-"Lichen_Epiphyte_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="hypspl"]<-"Moss_Hylocomnium"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="icmeri"]<-"Lichen_Crustose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="irisit"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="larlar"]<-"Tree_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="leddec"]<-"Shrub_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="loipro"]<-"Shrub_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="luparc"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="masric"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="melanelia"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="melhep"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="neparc"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="naparc"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="orange_Porpidia"]<-"Lichen_Crustose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="paramb"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="paromp"]<-"Lichen_Foliose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="parsul"]<-"Lichen_Foliose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="pedrac"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="pedsud"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="pelapt"]<-"Lichen_Foliose_Dark_Peltigera" #Should Peltigera be their own class
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="pelleu"]<-"Lichen_Foliose_Dark_Peltigera" #Should Peltigera be their own class
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="pelmal"]<-"Lichen_Foliose_Dark_Peltigera" #Should Peltigera be their own class
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="pelsca"]<-"Lichen_Foliose_Dark_Peltigera"  #Should Peltigera be their own class
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="petfri"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="picmar"]<-"Tree_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="picrub"]<-"Tree_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="pilaci"]<-"Lichen_Crustose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="pinstr"]<-"Tree_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="plagiomnium"]<-"Moss_Plagiomnium"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="popbal"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="popgra"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="prupen"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="plesch"]<-"Moss_Pleurozium"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="poljen"]<-"Moss_Polytrichum"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="poljun"]<-"Moss_Polytrichum"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="polstr"]<-"Moss_Polytrichum"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="polytrichum"]<-"Moss_Polytrichum"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="popbal"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="quartz"]<-"Rock"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="querub"]<-"Tree_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="raclan"]<-"Moss_Racomitrium"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="rhigeo"]<-"Lichen_Crustose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="rhyrug"]<-"Moss_Rhytidium"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="rhutyp"]<-"Shrub_Rosa"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="rosaci"]<-"Shrub_Rosa"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="rosasc"]<-"Shrub_Rosa"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="rubcam"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="rubcha"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="salala"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="salarb"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="salgla"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="sallan"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="salova"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="Salova"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="salpul"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="salric"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="sphagn"]<-"Moss_Sphagnum_other"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="sphfus"]<-"Moss_Sphagnum_fuscum"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="spruce bark"]<-"Wood_Coarse"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="stepas"]<-"Lichen_Fruticose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="stetas"]<-"Lichen_Fruticose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="thuocc"]<-"Tree_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="toefeldia"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="tomnit"]<-"Moss_Tomenthypnum"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="tragra"]<-"Lichen_Crustose_Light"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="tsucan"]<-"Tree_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="umbarc"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="umbhyp"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="usnlap"]<-"Lichen_Epiphyte_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="usnsca"]<-"Lichen_Epiphyte_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="vacvit"]<-"Shrub_Evergreen"       #????Ask other veg folks in AK, like Matt and JJ, what they think
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="vaculi"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="vulpin"]<-"Lichen_Epiphyte_Yellow"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="wooly_salix"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="SAPU15"]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="PEFR5"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="SAPU6"]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="ARFU2"]<-"Graminoid_Grass"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="DUFI"]<-"Graminoid_Grass"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="CAAQ"]<-"Graminoid_Sedge"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="ARLA2"]<-"Graminoid_Grass"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="ERAN6"]<-"Graminoid_Sedge"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="VAVI"]<-"Shrub_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="ALVI5" ]<-"Shrub_Alder"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="ARALA7"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="BEGL"  ]<-"Shrub_Betula"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="BENA"  ]<-"Shrub_Betula"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="BEPU4" ]<-"Shrub_Betula"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="DAFRF" ]<-"Unknown"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="DOFR"  ]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="DROCA2"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="EMNI"  ]<-"Shrub_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="EQAR"  ]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="ERVA4" ]<-"Graminoid_Sedge"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="HIERA" ]<-"Forb"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="KAPR"  ]<-"Shrub_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="LEDUM" ]<-"Shrub_Evergreen"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="RUCH"  ]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="SAG"   ]<-"Unknown"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="SAPH"  ]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="SARI4" ]<-"Shrub_Salix"
SpecLib_groups$Functional_group1[SpecLib_groups$Code_name=="VAUL"  ]<-"Dwarf_Shrub_Decid"






###Add column Functional_group2 (Courser than Code_name3 response variables)
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="abibal"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="acerub"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="acepen"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="aleoch"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="alnfru"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="alninc"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="arccen"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="arcnig"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="arcrub"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="arcsta"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="arctop"]<-"Unknown"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="asachr"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="aulpal"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="aultur"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="bare rock"]<-"Abiotic"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="bare_soil"]<-"Abiotic"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="betall"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="betnan"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="betneo"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="betpap"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="betpop"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="bryoria"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="calcan"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="carlin"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="carlyn"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="carram"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="castet"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="cerpur"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="cetisl"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="cetlae"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="claama"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="clacor"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="clacuc"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="clagra"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="clamit"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="claran"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="claste"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="clasty"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="clasul"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="claunc"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="dacarc"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="dead salix"]<-"Abiotic"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="dicranum"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="dryala"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="dryhyb"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="dryoct"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="empnig"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="equarv"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="equsyl"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="erivag"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="evemes"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="faggra"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="flacuc"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="flaniv"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="fraame"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="gravel"]<-"Abiotic"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="grey_rhizocarpon"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="herlan"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="hylspl"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="hypaus"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="hypspl"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="icmeri"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="irisit"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="larlar"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="leddec"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="loipro"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="luparc"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="masric"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="melanelia"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="melhep"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="neparc"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="naparc"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="orange_Porpidia"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="paramb"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="paromp"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="parsul"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="pedrac"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="pedsud"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="pelapt"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="pelleu"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="pelmal"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="pelsca"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="petfri"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="picmar"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="picrub"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="pilaci"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="pinstr"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="plagiomnium"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="popbal"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="popgra"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="prupen"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="plesch"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="poljen"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="poljun"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="polstr"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="polytrichum"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="popbal"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="quartz"]<-"Abiotic"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="querub"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="raclan"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="rhigeo"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="rhyrug"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="rhutyp"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="rosaci"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="rosasc"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="rubcam"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="rubcha"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="salala"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="salarb"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="salgla"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="sallan"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="salova"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="Salova"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="salpul"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="salric"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="sphagn"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="sphfus"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="spruce bark"]<-"Abiotic"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="stepas"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="stetas"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="thuocc"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="toefeldia"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="tomnit"]<-"Moss"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="tragra"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="tsucan"]<-"Tree"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="umbarc"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="umbhyp"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="usnlap"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="usnsca"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="vacvit"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="vaculi"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="vulpin"]<-"Lichen"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="wooly_salix"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="SAPU15"]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="PEFR5"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="SAPU6"]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="ARFU2"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="DUFI"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="CAAQ"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="ARLA2"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="ERAN6"]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="VAVI"]<-"Shrub"


SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="ALVI5" ]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="ARALA7"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="BEGL"  ]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="BENA"  ]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="BEPU4" ]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="DAFRF" ]<-"Unknown"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="DOFR"  ]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="DROCA2"]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="EMNI"  ]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="EQAR"  ]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="ERVA4" ]<-"Graminoid"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="HIERA" ]<-"Forb"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="KAPR"  ]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="LEDUM" ]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="RUCH"  ]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="SAG"   ]<-"Unknown"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="SAPH"  ]<-"Dwarf Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="SARI4" ]<-"Shrub"
SpecLib_groups$Functional_group2[SpecLib_groups$Code_name=="VAUL"  ]<-"Dwarf Shrub"


##Refine Fnc group 2 to collapse dwarf and shrub but separate evergreen from deciduos
SpecLib_groups<-SpecLib_groups %>%
mutate(
  Functional_group2 = ifelse(Functional_group1=="Tree_Decid", "Tree_Decid", 
                             ifelse(Functional_group1=="Tree_Evergreen", "Tree_Evergreen", 
                                    ifelse(Functional_group1=="Dwarf_Shrub_Decid", "Shrub_Decid",
                                           ifelse(Functional_group1=="Shrub_Betula","Shrub_Decid",
                                                  ifelse(Functional_group1=="Shrub_Alder","Shrub_Decid",
                                                         ifelse(Functional_group1=="Shrub_Evergreen","Shrub_Evergreen",
                                                                ifelse(Functional_group1=="Shrub_Rosa","Shrub_Decid",
                                                                       ifelse(Functional_group1=="Shrub_Salix","Shrub_Decid",
                                                                              ifelse(Functional_group1=="Lichen_Fruticose_Yellow","Lichen",
                                                                                     ifelse(Functional_group1=="Lichen_Foliose_Yellow","Lichen",
                                                                                            ifelse(Functional_group1=="Lichen_Epiphyte_Dark","Lichen",
                                                                                                   ifelse(Functional_group1=="Lichen_Fruticose_Dark","Lichen",
                                                                                                          ifelse(Functional_group1=="Lichen_Fruticose_Light","Lichen",
                                                                                                                 ifelse(Functional_group1=="Lichen_Epiphyte_Yellow","Lichen",
                                                                                                                        ifelse(Functional_group1=="Lichen_Crustose_Dark","Lichen",
                                                                                                                               ifelse(Functional_group1=="Lichen_Crustose_Light","Lichen",
                                                                                                                                      ifelse(Functional_group1=="Lichen_Foliose_Dark","Lichen",
                                                                                                                                             ifelse(Functional_group1=="Lichen_Foliose_Light","Lichen",
                                                                                                                                                    ifelse(Functional_group1=="Lichen_Foliose_Dark_Peltigera","Lichen", Functional_group2)))))))))))))))))))) #%>% dplyr::select(Functional_group2)

write.csv(SpecLib_groups,"Output/B_001_SC1_SpeciesTable.csv",row.names = F)
