# Creates a dataframe with all species and their corresponding functional groups
library (tidyverse)

# Creates column Class1
# PRN This is hard coded. How can we do this more automatically, like reading in a file of names?
SpecLib_groups<-data.frame("Class1"= c("abibal"
                                       ,"acerub"
                                       ,"acepen"
                                       ,"aleoch"
                                       ,"alnfru"
                                       ,"alninc"
                                       ,"arccen"
                                       ,"arcnig"
                                       ,"arcrub"
                                       ,"arcsta"
                                       ,"arctop"
                                       ,"asachr"
                                       ,"aulpal"
                                       ,"aultur"
                                       ,"bare rock"
                                       ,"bare_soil"
                                       ,"betall"
                                       ,"betnan"
                                       ,"betneo"
                                       ,"betpap"
                                       ,"betpop"
                                       ,"bryoria"
                                       ,"calcan"
                                       ,"carlin"
                                       ,"carlyn"
                                       ,"carram"
                                       ,"castet"
                                       ,"cerpur"
                                       ,"cetisl"
                                       ,"cetlae"
                                       ,"claama"
                                       ,"clacor"
                                       ,"clacuc"
                                       ,"clagra"
                                       ,"clamit"
                                       ,"claran"
                                       ,"claste"
                                       ,"clasty"
                                       ,"clasul"
                                       ,"claunc"
                                       ,"dacarc"
                                       ,"dead salix"
                                       ,"dicranum"
                                       ,"dryala"
                                       ,"dryhyb"
                                       ,"dryoct"
                                       ,"empnig"
                                       ,"equarv"
                                       ,"equsyl"
                                       ,"erivag"
                                       ,"evemes"
                                       ,"faggra"
                                       ,"flacuc"
                                       ,"flaniv"
                                       ,"fraame"
                                       ,"gravel"
                                       ,"grey_rhizocarpon"
                                       ,"herlan"
                                       ,"hylspl"
                                       ,"hypaus"
                                       ,"hypspl"
                                       ,"icmeri"
                                       ,"irisit"
                                       ,"larlar"
                                       ,"leddec"
                                       ,"loipro"
                                       ,"luparc"
                                       ,"masric"
                                       ,"melanelia"
                                       ,"melhep"
                                       ,"neparc"
                                       ,"naparc"
                                       ,"orange_Porpidia"
                                       ,"paramb"
                                       ,"paromp"
                                       ,"parsul"
                                       ,"pedrac"
                                       ,"pedsud"
                                       ,"pelapt"
                                       ,"pelleu"
                                       ,"pelmal"
                                       ,"pelsca"
                                       ,"petfri"
                                       ,"picmar"
                                       ,"picrub"
                                       ,"pilaci"
                                       ,"pinstr"
                                       ,"plagiomnium"
                                       ,"popbal"
                                       ,"popgra"
                                       ,"prupen"
                                       ,"plesch"
                                       ,"poljen"
                                       ,"poljun"
                                       ,"polstr"
                                       ,"polytrichum"
                                       ,"popbal"
                                       ,"quartz"
                                       ,"querub"
                                       ,"raclan"
                                       ,"rhigeo"
                                       ,"rhyrug"
                                       ,"rhutyp"
                                       ,"rosaci"
                                       ,"rosasc"
                                       ,"rubcam"
                                       ,"rubcha"
                                       ,"salala"
                                       ,"salarb"
                                       ,"salgla"
                                       ,"sallan"
                                       ,"salova"
                                       ,"Salova"
                                       ,"salpul"
                                       ,"salric"
                                       ,"sphagn"
                                       ,"sphfus"
                                       ,"spruce bark"
                                       ,"stepas"
                                       ,"stetas"
                                       ,"thuocc"
                                       ,"toefeldia"
                                       ,"tomnit"
                                       ,"tragra"
                                       ,"tsucan"
                                       ,"umbarc"
                                       ,"umbhyp"
                                       ,"usnlap"
                                       ,"usnsca"
                                       ,"vacvit"
                                       ,"vaculi"
                                       ,"vulpin"
                                       ,"wooly_salix"
                                       ,"SAPU15"
                                       ,"PEFR5"
                                       ,"SAPU6"
                                       ,"ARFU2"
                                       ,"DUFI"
                                       ,"CAAQ"
                                       ,"ARLA2"
                                       ,"ERAN6"
                                       ,"VAVI"))

# Add column Class2 (SPECIES) to spectral library
# PRN This is also hard coded. How to automate from user input?
SpecLib_groups$Class2[SpecLib_groups$Class1=="abibal"]<-"Abies balsamea"
SpecLib_groups$Class2[SpecLib_groups$Class1=="acerub"]<-"Acer rubrum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="acepen"]<-"Acer pensylvanicum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="aleoch"]<-"Alectoria ochroleuca"
SpecLib_groups$Class2[SpecLib_groups$Class1=="alnfru"]<-"Alnus sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="alninc"]<-"Alnus Incana"
SpecLib_groups$Class2[SpecLib_groups$Class1=="arccen"]<-"Arctocetraria centrifuga"
SpecLib_groups$Class2[SpecLib_groups$Class1=="arcnig"]<-"Arctostaphyllos"
SpecLib_groups$Class2[SpecLib_groups$Class1=="arcrub"]<-"Arctostaphyllos"
SpecLib_groups$Class2[SpecLib_groups$Class1=="arcsta"]<-"Arctostaphyllos"
SpecLib_groups$Class2[SpecLib_groups$Class1=="arctop"]<-"Unknown"
SpecLib_groups$Class2[SpecLib_groups$Class1=="asachr"]<-"Asahinea chrysantha"
SpecLib_groups$Class2[SpecLib_groups$Class1=="aulpal"]<-"Aulacomnium palustre"
SpecLib_groups$Class2[SpecLib_groups$Class1=="aultur"]<-"Aulacomnium turgidum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="bare rock"]<-"Bare Rock"
SpecLib_groups$Class2[SpecLib_groups$Class1=="bare_soil"]<-"Bare Soil"
SpecLib_groups$Class2[SpecLib_groups$Class1=="betall"]<-"Betula alleghaniensis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="betnan"]<-"Betula nana"
SpecLib_groups$Class2[SpecLib_groups$Class1=="betneo"]<-"Betula neoalaskana"
SpecLib_groups$Class2[SpecLib_groups$Class1=="betpap"]<-"Betula papyrifera"
SpecLib_groups$Class2[SpecLib_groups$Class1=="betpop"]<-"Betula populifolia"
SpecLib_groups$Class2[SpecLib_groups$Class1=="bryoria"]<-"Bryoria sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="calcan"]<-"Calamogrostis sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="carlin"]<-"Carex sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="carlyn"]<-"Carex sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="carram"]<-"Carex sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="castet"]<-"Cassiope tetragona"
SpecLib_groups$Class2[SpecLib_groups$Class1=="cerpur"]<-"Ceratadon purpureus"
SpecLib_groups$Class2[SpecLib_groups$Class1=="cetisl"]<-"Cetraria islandica"
SpecLib_groups$Class2[SpecLib_groups$Class1=="cetlae"]<-"Cetraria laevigata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="claama"]<-"Cladonia amaurocraea"
SpecLib_groups$Class2[SpecLib_groups$Class1=="clacor"]<-"Cladonia cornuta"
SpecLib_groups$Class2[SpecLib_groups$Class1=="clacuc"]<-"Flavocetraria cucculata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="clagra"]<-"Cladonia gracilis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="clamit"]<-"Cladonia mitis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="claran"]<-"Cladonia rangiferina"
SpecLib_groups$Class2[SpecLib_groups$Class1=="claste"]<-"Cladonia steallaris"
SpecLib_groups$Class2[SpecLib_groups$Class1=="clasty"]<-"Cladonia stygia"
SpecLib_groups$Class2[SpecLib_groups$Class1=="clasul"]<-"Cladonia sulphurina"
SpecLib_groups$Class2[SpecLib_groups$Class1=="claunc"]<-"Cladonia uncialis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="dacarc"]<-"Dactylina arctica"
SpecLib_groups$Class2[SpecLib_groups$Class1=="dead salix"]<-"Dead Salix"
SpecLib_groups$Class2[SpecLib_groups$Class1=="dicranum"]<-"Dicranum sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="dryala"]<-"Dryas alleghenies"
SpecLib_groups$Class2[SpecLib_groups$Class1=="dryhyb"]<-"Dryas sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="dryoct"]<-"Dryas octopetala"
SpecLib_groups$Class2[SpecLib_groups$Class1=="empnig"]<-"Empetrum nigrum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="equarv"]<-"Equisetum arvense"
SpecLib_groups$Class2[SpecLib_groups$Class1=="equsyl"]<-"Equisetum sylvaticum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="erivag"]<-"Eriophorum vaginatum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="evemes"]<-"Evernia mesomorpha"
SpecLib_groups$Class2[SpecLib_groups$Class1=="faggra"]<-"Fagus grandifolia"
SpecLib_groups$Class2[SpecLib_groups$Class1=="flacuc"]<-"Flavocetraria cucculata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="flaniv"]<-"Flavocetraria nivalis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="fraame"]<-"Fraxinus americana"
SpecLib_groups$Class2[SpecLib_groups$Class1=="gravel"]<-"Bare Soil"
SpecLib_groups$Class2[SpecLib_groups$Class1=="grey_rhizocarpon"]<-"Rhizocarpon sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="herlan"]<-"Heracleum lanatum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="hylspl"]<-"Hylocomium splendens"
SpecLib_groups$Class2[SpecLib_groups$Class1=="hypaus"]<-"Hypogymnia austerodes"
SpecLib_groups$Class2[SpecLib_groups$Class1=="hypspl"]<-"Hylocomium splendens"
SpecLib_groups$Class2[SpecLib_groups$Class1=="icmeri"]<-"Icmadophila ericetorum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="irisit"]<-"Iris sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="larlar"]<-"Larix Larcina"
SpecLib_groups$Class2[SpecLib_groups$Class1=="leddec"]<-"Ledum decumbens"
SpecLib_groups$Class2[SpecLib_groups$Class1=="loipro"]<-"Loisleuria procumbens"
SpecLib_groups$Class2[SpecLib_groups$Class1=="luparc"]<-"Lupinus sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="masric"]<-"Masonhalea richardsonii"
SpecLib_groups$Class2[SpecLib_groups$Class1=="melanelia"]<-"Melanelia sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="melhep"]<-"Melanelia sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="neparc"]<-"Nephroma arcticum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="naparc"]<-"Nephroma arcticum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="orange_Porpidia"]<-"Porpidia sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="paramb"]<-"Parmeliopsis ambigua"
SpecLib_groups$Class2[SpecLib_groups$Class1=="paromp"]<-"Parmelia omphalodes"
SpecLib_groups$Class2[SpecLib_groups$Class1=="parsul"]<-"Parmelis sulcata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="pedrac"]<-"Pedicularis racemosa"
SpecLib_groups$Class2[SpecLib_groups$Class1=="pedsud"]<-"Pedicularis sudetica"
SpecLib_groups$Class2[SpecLib_groups$Class1=="pelapt"]<-"Peltigera apthosa"
SpecLib_groups$Class2[SpecLib_groups$Class1=="pelleu"]<-"Peltigers leucophlebia"
SpecLib_groups$Class2[SpecLib_groups$Class1=="pelmal"]<-"Peltigera malacea"
SpecLib_groups$Class2[SpecLib_groups$Class1=="pelsca"]<-"Peltigera scabrata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="petfri"]<-"Petasites frigida"
SpecLib_groups$Class2[SpecLib_groups$Class1=="picmar"]<-"Picea mariana"
SpecLib_groups$Class2[SpecLib_groups$Class1=="picrub"]<-"Picea rubens"
SpecLib_groups$Class2[SpecLib_groups$Class1=="pilaci"]<-"Pilophorus acicularis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="pinstr"]<-"Pinus strobus"
SpecLib_groups$Class2[SpecLib_groups$Class1=="plagiomnium"]<-"Plagiomnium sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="plesch"]<-"Pleurozium schreberi"
SpecLib_groups$Class2[SpecLib_groups$Class1=="poljen"]<-"Polytrichum juniperinum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="poljun"]<-"Polytrichum juniperinum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="polstr"]<-"Polytrichum strictum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="polytrichum"]<-"Polytrichum sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="popbal"]<-"Populus balsamifera"
SpecLib_groups$Class2[SpecLib_groups$Class1=="popgra"]<-"Populus grandidentata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="prupen"]<-"Prunus pensylvanica"
SpecLib_groups$Class2[SpecLib_groups$Class1=="quartz"]<-"Quartz"
SpecLib_groups$Class2[SpecLib_groups$Class1=="querub"]<-"Quercus Rubra"
SpecLib_groups$Class2[SpecLib_groups$Class1=="raclan"]<-"Racomitrium lanoiginosum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="rhigeo"]<-"Rhizocarpon geographicum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="rhutyp"]<-"Rhus typhina"
SpecLib_groups$Class2[SpecLib_groups$Class1=="rhyrug"]<-"Rhytidum rugosum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="rosaci"]<-"Rosa acicularis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="rosasc"]<-"Rosa acicularis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="rubcam"]<-"Rubus sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="rubcha"]<-"Rubus sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="salala"]<-"Salix alaxensis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="salarb"]<-"Salix arbusculoides"
SpecLib_groups$Class2[SpecLib_groups$Class1=="salgla"]<-"Salix glauca"
SpecLib_groups$Class2[SpecLib_groups$Class1=="sallan"]<-"Salix lanata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="salova"]<-"Salix ovalifolia"
SpecLib_groups$Class2[SpecLib_groups$Class1=="Salova"]<-"Salix ovalifolia"
SpecLib_groups$Class2[SpecLib_groups$Class1=="salpul"]<-"Salix pulchra"
SpecLib_groups$Class2[SpecLib_groups$Class1=="salric"]<-"Salix richardsonii"
SpecLib_groups$Class2[SpecLib_groups$Class1=="sphagn"]<-"Sphagnum sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="sphfus"]<-"Sphagnum fuscum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="spruce bark"]<-"Pices (bark)"
SpecLib_groups$Class2[SpecLib_groups$Class1=="stepas"]<-"Stereocaulon sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="stetas"]<-"Stereocaulon sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="thuocc"]<-"Thuja occidentalis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="toefeldia"]<-"Toefeldia sp."
SpecLib_groups$Class2[SpecLib_groups$Class1=="tomnit"]<-"Tomenthypnum nitens"
SpecLib_groups$Class2[SpecLib_groups$Class1=="tragra"]<-"Trapelopsis granulosa"
SpecLib_groups$Class2[SpecLib_groups$Class1=="tsucan"]<-"Tsuga canadensis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="umbarc"]<-"Umbilicaria arctica"
SpecLib_groups$Class2[SpecLib_groups$Class1=="umbhyp"]<-"Umbilicaria hyperborea"
SpecLib_groups$Class2[SpecLib_groups$Class1=="usnlap"]<-"Usnea lapponica"
SpecLib_groups$Class2[SpecLib_groups$Class1=="usnsca"]<-"Usnea scabrata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="vacvit"]<-"Vaccinium vitis-idea"
SpecLib_groups$Class2[SpecLib_groups$Class1=="vaculi"]<-"Vaccinium uliginosum"
SpecLib_groups$Class2[SpecLib_groups$Class1=="vulpin"]<-"Vulpicida pinastri"
SpecLib_groups$Class2[SpecLib_groups$Class1=="wooly_salix"]<-"Salix (wooly)"
SpecLib_groups$Class2[SpecLib_groups$Class1=="SAPU15"]<-"Salix pulchra"
SpecLib_groups$Class2[SpecLib_groups$Class1=="PEFR5"]<-"Pestasites frigidus"
SpecLib_groups$Class2[SpecLib_groups$Class1=="SAPU6"]<-"Saxifraga punctata"
SpecLib_groups$Class2[SpecLib_groups$Class1=="ARFU2"]<-"Arctophila fulva"
SpecLib_groups$Class2[SpecLib_groups$Class1=="DUFI"]<-"Dupontia fisheri"
SpecLib_groups$Class2[SpecLib_groups$Class1=="CAAQ"]<-"Carex aquatilis"
SpecLib_groups$Class2[SpecLib_groups$Class1=="ARLA2"]<-"Arctagrostis latifolia"
SpecLib_groups$Class2[SpecLib_groups$Class1=="ERAN6"]<-"Eriophorum angustifolium"
SpecLib_groups$Class2[SpecLib_groups$Class1=="VAVI"]<-"Vaccinium vitis-idea"

###Add column Class3 (Courser response variables)
# PRN This is hard coded. We should be using a look up table for functional group (Class 3) each plant species (Class 2) is.
SpecLib_groups$Class3[SpecLib_groups$Class1=="abibal"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="acerub"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="acepen"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="aleoch"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="alnfru"]<-"Shrub_Alder"
SpecLib_groups$Class3[SpecLib_groups$Class1=="alninc"]<-"Shrub_Alder"
SpecLib_groups$Class3[SpecLib_groups$Class1=="arccen"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="arcnig"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="arcrub"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="arcsta"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="arctop"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="asachr"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="aulpal"]<-"Moss_Aulacomnium"
SpecLib_groups$Class3[SpecLib_groups$Class1=="aultur"]<-"Moss_Aulacomnium"
SpecLib_groups$Class3[SpecLib_groups$Class1=="bare rock"]<-"Rock"
SpecLib_groups$Class3[SpecLib_groups$Class1=="bare_soil"]<-"Soil"
SpecLib_groups$Class3[SpecLib_groups$Class1=="betall"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="betnan"]<-"Shrub_Betula"
SpecLib_groups$Class3[SpecLib_groups$Class1=="betneo"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="betpap"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="betpop"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="bryoria"]<-"Lichen_Epiphyte_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="calcan"]<-"Graminoid_Grass"
SpecLib_groups$Class3[SpecLib_groups$Class1=="carlin"]<-"Graminoid_Sedge"
SpecLib_groups$Class3[SpecLib_groups$Class1=="carlyn"]<-"Graminoid_Sedge"
SpecLib_groups$Class3[SpecLib_groups$Class1=="carram"]<-"Graminoid_Sedge"
SpecLib_groups$Class3[SpecLib_groups$Class1=="castet"]<-"Shrub_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="cerpur"]<-"Moss_Ceratadon"
SpecLib_groups$Class3[SpecLib_groups$Class1=="cetisl"]<-"Lichen_Fruticose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="cetlae"]<-"Lichen_Fruticose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="claama"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="clacor"]<-"Lichen_Fruticose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="clacuc"]<-"Lichen_Fruticose_Dark" #Check this. Might actually be flacuc
SpecLib_groups$Class3[SpecLib_groups$Class1=="clagra"]<-"Lichen_Fruticose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="clamit"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="claran"]<-"Lichen_Fruticose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="claste"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="clasty"]<-"Lichen_Fruticose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="clasul"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="claunc"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="dacarc"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="dead salix"]<-"Litter"
SpecLib_groups$Class3[SpecLib_groups$Class1=="dicranum"]<-"Moss_Dicranum"
SpecLib_groups$Class3[SpecLib_groups$Class1=="dryala"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="dryhyb"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="dryoct"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="empnig"]<-"Shrub_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="equarv"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="equsyl"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="erivag"]<-"Graminoid_Sedge"
SpecLib_groups$Class3[SpecLib_groups$Class1=="evemes"]<-"Lichen_Epiphyte_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="faggra"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="flacuc"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="flaniv"]<-"Lichen_Fruticose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="fraame"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="gravel"]<-"Soil"
SpecLib_groups$Class3[SpecLib_groups$Class1=="grey_rhizocarpon"]<-"Lichen_Crustose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="herlan"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="hylspl"]<-"Moss_Hylocomnium"
SpecLib_groups$Class3[SpecLib_groups$Class1=="hypaus"]<-"Lichen_Epiphyte_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="hypspl"]<-"Moss_Hylocomnium"
SpecLib_groups$Class3[SpecLib_groups$Class1=="icmeri"]<-"Lichen_Crustose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="irisit"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="larlar"]<-"Tree_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="leddec"]<-"Shrub_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="loipro"]<-"Shrub_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="luparc"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="masric"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="melanelia"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="melhep"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="neparc"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="naparc"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="orange_Porpidia"]<-"Lichen_Crustose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="paramb"]<-"Lichen_Foliose_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="paromp"]<-"Lichen_Foliose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="parsul"]<-"Lichen_Foliose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="pedrac"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="pedsud"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="pelapt"]<-"Lichen_Foliose_Dark_Peltigera" #Should Peltigera be their own class
SpecLib_groups$Class3[SpecLib_groups$Class1=="pelleu"]<-"Lichen_Foliose_Dark_Peltigera" #Should Peltigera be their own class
SpecLib_groups$Class3[SpecLib_groups$Class1=="pelmal"]<-"Lichen_Foliose_Dark_Peltigera" #Should Peltigera be their own class
SpecLib_groups$Class3[SpecLib_groups$Class1=="pelsca"]<-"Lichen_Foliose_Dark_Peltigera"  #Should Peltigera be their own class
SpecLib_groups$Class3[SpecLib_groups$Class1=="petfri"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="picmar"]<-"Tree_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="picrub"]<-"Tree_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="pilaci"]<-"Lichen_Crustose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="pinstr"]<-"Tree_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="plagiomnium"]<-"Moss_Plagiomnium"
SpecLib_groups$Class3[SpecLib_groups$Class1=="popbal"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="popgra"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="prupen"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="plesch"]<-"Moss_Pleurozium"
SpecLib_groups$Class3[SpecLib_groups$Class1=="poljen"]<-"Moss_Polytrichum"
SpecLib_groups$Class3[SpecLib_groups$Class1=="poljun"]<-"Moss_Polytrichum"
SpecLib_groups$Class3[SpecLib_groups$Class1=="polstr"]<-"Moss_Polytrichum"
SpecLib_groups$Class3[SpecLib_groups$Class1=="polytrichum"]<-"Moss_Polytrichum"
SpecLib_groups$Class3[SpecLib_groups$Class1=="popbal"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="quartz"]<-"Rock"
SpecLib_groups$Class3[SpecLib_groups$Class1=="querub"]<-"Tree_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="raclan"]<-"Moss_Racomitrium"
SpecLib_groups$Class3[SpecLib_groups$Class1=="rhigeo"]<-"Lichen_Crustose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="rhyrug"]<-"Moss_Rhytidium"
SpecLib_groups$Class3[SpecLib_groups$Class1=="rhutyp"]<-"Shrub_Rosa"
SpecLib_groups$Class3[SpecLib_groups$Class1=="rosaci"]<-"Shrub_Rosa"
SpecLib_groups$Class3[SpecLib_groups$Class1=="rosasc"]<-"Shrub_Rosa"
SpecLib_groups$Class3[SpecLib_groups$Class1=="rubcam"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="rubcha"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="salala"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="salarb"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="salgla"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="sallan"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="salova"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="Salova"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="salpul"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="salric"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="sphagn"]<-"Moss_Sphagnum_other"
SpecLib_groups$Class3[SpecLib_groups$Class1=="sphfus"]<-"Moss_Sphagnum_fuscum"
SpecLib_groups$Class3[SpecLib_groups$Class1=="spruce bark"]<-"Wood_Coarse"
SpecLib_groups$Class3[SpecLib_groups$Class1=="stepas"]<-"Lichen_Fruticose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="stetas"]<-"Lichen_Fruticose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="thuocc"]<-"Tree_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="toefeldia"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="tomnit"]<-"Moss_Tomenthypnum"
SpecLib_groups$Class3[SpecLib_groups$Class1=="tragra"]<-"Lichen_Crustose_Light"
SpecLib_groups$Class3[SpecLib_groups$Class1=="tsucan"]<-"Tree_Evergreen"
SpecLib_groups$Class3[SpecLib_groups$Class1=="umbarc"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="umbhyp"]<-"Lichen_Foliose_Dark"
SpecLib_groups$Class3[SpecLib_groups$Class1=="usnlap"]<-"Lichen_Epiphyte_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="usnsca"]<-"Lichen_Epiphyte_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="vacvit"]<-"Shrub_Evergreen"       #????Ask other veg folks in AK, like Matt and JJ, what they think
SpecLib_groups$Class3[SpecLib_groups$Class1=="vaculi"]<-"Dwarf_Shrub_Decid"
SpecLib_groups$Class3[SpecLib_groups$Class1=="vulpin"]<-"Lichen_Epiphyte_Yellow"
SpecLib_groups$Class3[SpecLib_groups$Class1=="wooly_salix"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="SAPU15"]<-"Shrub_Salix"
SpecLib_groups$Class3[SpecLib_groups$Class1=="PEFR5"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="SAPU6"]<-"Forb"
SpecLib_groups$Class3[SpecLib_groups$Class1=="ARFU2"]<-"Graminoid_Grass"
SpecLib_groups$Class3[SpecLib_groups$Class1=="DUFI"]<-"Graminoid_Grass"
SpecLib_groups$Class3[SpecLib_groups$Class1=="CAAQ"]<-"Graminoid_Sedge"
SpecLib_groups$Class3[SpecLib_groups$Class1=="ARLA2"]<-"Graminoid_Grass"
SpecLib_groups$Class3[SpecLib_groups$Class1=="ERAN6"]<-"Graminoid_Sedge"
SpecLib_groups$Class3[SpecLib_groups$Class1=="VAVI"]<-"Shrub_Evergreen"

###Add column Class4 (Courser than Class13 response variables)
SpecLib_groups$Class4[SpecLib_groups$Class1=="abibal"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="acerub"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="acepen"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="aleoch"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="alnfru"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="alninc"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="arccen"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="arcnig"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="arcrub"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="arcsta"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="arctop"]<-"Unknown"
SpecLib_groups$Class4[SpecLib_groups$Class1=="asachr"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="aulpal"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="aultur"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="bare rock"]<-"Abiotic"
SpecLib_groups$Class4[SpecLib_groups$Class1=="bare_soil"]<-"Abiotic"
SpecLib_groups$Class4[SpecLib_groups$Class1=="betall"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="betnan"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="betneo"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="betpap"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="betpop"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="bryoria"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="calcan"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="carlin"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="carlyn"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="carram"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="castet"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="cerpur"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="cetisl"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="cetlae"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="claama"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="clacor"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="clacuc"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="clagra"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="clamit"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="claran"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="claste"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="clasty"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="clasul"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="claunc"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="dacarc"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="dead salix"]<-"Abiotic"
SpecLib_groups$Class4[SpecLib_groups$Class1=="dicranum"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="dryala"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="dryhyb"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="dryoct"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="empnig"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="equarv"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="equsyl"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="erivag"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="evemes"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="faggra"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="flacuc"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="flaniv"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="fraame"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="gravel"]<-"Abiotic"
SpecLib_groups$Class4[SpecLib_groups$Class1=="grey_rhizocarpon"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="herlan"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="hylspl"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="hypaus"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="hypspl"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="icmeri"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="irisit"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="larlar"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="leddec"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="loipro"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="luparc"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="masric"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="melanelia"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="melhep"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="neparc"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="naparc"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="orange_Porpidia"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="paramb"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="paromp"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="parsul"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="pedrac"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="pedsud"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="pelapt"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="pelleu"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="pelmal"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="pelsca"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="petfri"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="picmar"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="picrub"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="pilaci"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="pinstr"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="plagiomnium"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="popbal"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="popgra"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="prupen"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="plesch"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="poljen"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="poljun"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="polstr"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="polytrichum"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="popbal"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="quartz"]<-"Abiotic"
SpecLib_groups$Class4[SpecLib_groups$Class1=="querub"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="raclan"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="rhigeo"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="rhyrug"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="rhutyp"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="rosaci"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="rosasc"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="rubcam"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="rubcha"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="salala"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="salarb"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="salgla"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="sallan"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="salova"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="Salova"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="salpul"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="salric"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="sphagn"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="sphfus"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="spruce bark"]<-"Abiotic"
SpecLib_groups$Class4[SpecLib_groups$Class1=="stepas"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="stetas"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="thuocc"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="toefeldia"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="tomnit"]<-"Moss"
SpecLib_groups$Class4[SpecLib_groups$Class1=="tragra"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="tsucan"]<-"Tree"
SpecLib_groups$Class4[SpecLib_groups$Class1=="umbarc"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="umbhyp"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="usnlap"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="usnsca"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="vacvit"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="vaculi"]<-"Dwarf Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="vulpin"]<-"Lichen"
SpecLib_groups$Class4[SpecLib_groups$Class1=="wooly_salix"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="SAPU15"]<-"Shrub"
SpecLib_groups$Class4[SpecLib_groups$Class1=="PEFR5"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="SAPU6"]<-"Forb"
SpecLib_groups$Class4[SpecLib_groups$Class1=="ARFU2"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="DUFI"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="CAAQ"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="ARLA2"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="ERAN6"]<-"Graminoid"
SpecLib_groups$Class4[SpecLib_groups$Class1=="VAVI"]<-"Shrub"

write.csv(SpecLib_groups,"Output/B_001_Species_Table.csv",row.names = F)

